name: trackfi
description: "A premium Flutter fintech application."
publish_to: 'none'

version: 1.18.0+24

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  go_router: ^16.0.0
  provider: ^6.1.4
  flutter_riverpod: ^2.6.1
  flutter_dotenv: ^5.2.1
  firebase_core: ^3.15.1
  flutter_secure_storage: ^9.2.4
  flex_color_scheme: ^8.2.0
  flutter_animate: ^4.5.0
  gap: ^3.0.1
  riverpod_annotation: ^2.6.1
  local_auth: ^2.3.0
  crypto: ^3.0.6
  local_auth_darwin: ^1.5.0
  local_auth_android: ^1.0.49
  sentry_flutter: ^9.4.0
  sqflite: ^2.4.2
  path: ^1.9.1
  http: ^1.4.0
  package_info_plus: ^8.3.0
  money2: ^6.0.3
  meta: ^1.16.0
  encrypt: ^5.0.3
  uuid: ^4.5.1
  fl_chart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - lib/core/config/.env.ini
    - assets/currency/currencies.json

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic